config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post '/rsvp', to: 'attendings#create'

  delete '/unrsvp', to: 'attendings#destroy'

  resources :users, only: [:new, :create, :show]

  resources :events, only: [:show, :new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :event_attendings, :foreign_key => :guest_event_id, dependent: :destroy
	has_many :guests, :through => :event_attendings, :source => :event_guest
	belongs_to :host, :class_name => "User"
	default_scope -> { order(date: :desc, time: :desc) }

	validates :title, presence: true, length: { maximum: 30 }
	validates :description, length: { maximum: 250 }
	validates :location, presence: true, length: { maximum: 250 }
	validates :date, presence: true
	validate :ensure_date_has_not_passed
	validates :time, presence: true

	def self.upcoming
		Event.where("date >= ?", Date.current)
	end

	def self.past
		Event.where("date < ?", Date.current)
	end

	def attending?(user)
		guests.include?(user)
	end

	def upcoming?
		date >= Date.current
	end

	private

		def ensure_date_has_not_passed
			if ( date.present? && date < Date.today )
				errors.add(:date, "cannot be before #{Date.today}")
			end
		end

end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
	belongs_to :event_guest, :class_name => "User"
	belongs_to :guest_event, :class_name => "Event"
  validates :event_guest, presence: true
  validates :guest_event, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save :email_to_downcase

	has_many :event_attendings, :foreign_key => :event_guest_id, dependent: :destroy
	has_many :confirmed_events, :through => :event_attendings, :source => :guest_event
	has_many :hosted_events, :foreign_key => "host_id", :class_name => "Event", dependent: :destroy

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL }
	has_secure_password
	validates :password, presence: true, length: { minimum: 8 }

	def event_creator?(host)
		self == host
	end

	def hosted_feed
		Event.where("host_id = ?", id)
	end

	def attending_feed
		Event.where("event_guest_id = ?", id)
	end

  def attend(event)
    confirmed_events << event
  end

  def unattend(event)
    confirmed_events.delete(event)
  end

  def attending?(event)
    confirmed_events.include?(event)
  end

	private

		def email_to_downcase
			email.downcase!
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController
	before_action :check_user_login

	def create
		event = Event.find_by(id: params[:event_id])
		if event.nil?
			flash[:danger] = "The event does not exist."
			redirect_to root_url
    else
      current_user.attend(event)
			flash[:success] = "You have successfully confirmed your attendance!"
			redirect_to event_path(event)
		end
	end

	def destroy
    event = Event.find_by(id: params[:event_id])
    current_user.unattend(event)
		flash[:success] = "RSVP successfully cancelled."
		redirect_back(fallback_location: root_url)
	end

	private

		def check_user_login
  		if !logged_in?
  			flash[:info] = "You must first log in to complete this action."
  			redirect_back(fallback_location: root_url)
  		end
  	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :check_user_login
	before_action :check_correct_user, only: :destroy

  def show
  	@event = Event.find_by(id: params[:id])
  end

  def new
  	@event = current_user.hosted_events.build
  end

  def create
  	@event = current_user.hosted_events.build(event_params)
  	if @event.save
  		flash[:success] = "Event successfully created!"
  		redirect_to @event
  	else
  		flash.now[:danger] = "Event creation failed."
  		render 'new'
  	end
  end

  def destroy
  	@event.destroy
  	flash[:success] == "Event successfully removed."
  	redirect_to root_url
  end

  private

  	def event_params
  		params.require(:event).permit(:title, :description, :date, :time, :location)
  	end

  	def check_user_login
  		if !logged_in?
  			flash[:info] = "You must first log in to complete this action."
  			redirect_back(fallback_location: root_url)
  		end
  	end

  	def check_correct_user
  		@event = Event.find_by(id: params[:id])
  		if !current_user.event_creator?(@event.host)
  			flash[:danger] = "You may only delete an event that you created."
  			redirect_back(fallback_location: root_url)
  		end
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		login user
  		flash[:success] = "Welcome back, #{user.name}!"
  		redirect_to user
  	else
  		flash.now[:danger] = "Incorrect user/password combination"
  		render 'new'
  	end
  end

  def destroy
  	logout if logged_in?
  	redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@upcoming_event_feed = Event.upcoming.paginate(page: params[:page])
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user_login, only: :show

  def show
  	@user = User.find(params[:id])
    @upcoming_hosted_event_feed = @user.hosted_events.upcoming
    @past_hosted_event_feed = @user.hosted_events.past
    @upcoming_attending_event_feed = @user.confirmed_events.upcoming
    @past_attending_event_feed = @user.confirmed_events.past
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      login @user
  		flash[:success] = "Account successfully created!"
  		redirect_to @user
  	else
  		flash.now[:danger] = "User signup failed."
  		render 'new'
  	end
  end

  private

    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def check_user_login
      if !logged_in?
        flash[:info] = "You must first log in to complete this action."
        redirect_back(fallback_location: root_url)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title="")
		site_title = "Event Manager"
		if page_title.empty?
			site_title
		else
			page_title + " | " + site_title
		end
	end
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		end
	end

	def current_user?(user)
		user == current_user
	end

	def logout
		session.delete(:user_id)
		@current_user = nil
	end

	def logged_in?
		!current_user.nil?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class='event-box'>
	<h2><%= link_to event.title, event_path(event) %></h2>
	<span>Location: <%= event.location %></span><br>
	<span><%= event.date.strftime("%B %e, %Y") %> | <%= event.time.strftime("%l:%M %p") %></span>
	<br>
	<br>

	<% if logged_in? %>
		<% if current_user.event_creator?(event.host) %>
			<%= link_to "delete", event_path(event), method: :delete, data: { confirm: "Delete this event?" } %>
		<% elsif event.upcoming? %>
			<% if !event.attending?(current_user) %>
				<%= link_to "RSVP", rsvp_path(:event_id => event.id), method: :create %>
			<% else %>
				<%= link_to "Cancel RSVP", unrsvp_path(:event_id => event.id), method: :delete, data: { confirm: "Cancel RSVP?" } %>
			<% end %>
		<% end %>
	<% end %>
</div>

app/views/events/new.html.erb
<%= provide(:page_title, "Create event") %>
<h1 class='center'>Create event</h1>


<div class='row'>
	<div class='col-md-6 col-md-offset-3'>

		<%= form_for @event do |f| %>
	
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>

			<%= f.label :date %>
			<%= f.date_field :date, class: 'form-control' %>

			<%= f.label :time %>
			<%= f.time_field :time, class: 'form-control' %>

			<%= f.label :location %>
			<%= f.text_field :location, class: 'form-control' %>

			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>

			<%= f.submit 'Create event', class: 'btn btn-primary' %>

		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<%= provide(:page_title, @event.title) %>

<div class='row'>
	<div class='col-md-6'>
		<h1><%= @event.title %></h1>
		<h3>Hosted by: <%= link_to @event.host.name, user_path(@event.host.id) %></h3>
		<h3><%= @event.date.strftime("%B %e, %Y") %> <%= @event.time.strftime("%l:%M %p") %></h3>
		<h3><%= @event.location %></h3>
		<br>
		<p class='event-description'><%= @event.description %></p>

		<% if logged_in? %>
			<% if current_user.event_creator?(@event.host) %>
				<br>
				<%= link_to "delete", event_path(@event), method: :delete, data: { confirm: "Delete this event?" }, class: 'event-options' %>
			<% elsif @event.upcoming? %>
				<br>
				<% if !@event.attending?(current_user) %>
					<%= link_to "RSVP", rsvp_path(:event_id => @event.id), method: :create, class: 'event-options' %>
				<% else %>
					<%= link_to "Cancel RSVP", unrsvp_path(:event_id => @event.id), method: :delete, data: { confirm: "Cancel RSVP?" }, class: 'event-options' %>
				<% end %>
			<% end %>
		<% end %>

	</div>

	<div class='col-md-6'>
		<h1>Attending (<%= @event.guests.count %>)</h1>
		<div class='users-attending'>
			<% if @event.guests.any? %>
				<ul>
					<% @event.guests.each do |guest| %>
						<li><%= link_to guest.name, user_path(guest) %></li>
					<% end %>
				</ul>
			<% else %>
				<p class='no-guests'>No guests are currently attending this event.</p>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class='navbar navbar-inverse'>
	<div class='container'>
		<%= link_to "Event Manager", root_path, class: 'logo' %>
		<nav>
			<ul class='nav navbar-nav navbar-right'>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<% if logged_in? %>
					<li><%= link_to current_user.name, user_path(current_user) %></li>
					<li><%= link_to "Logout", logout_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign up", signup_path %></li>
					<li><%= link_to "Login", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:page_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class='container'>
	  	<% flash.each do | msg_type, msg | %>
	  		<%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
  		<% end %>
    	<%= yield %>
  	</div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class='error_explanation'>
		<div class='alert alert-danger'>
			<%= pluralize(object.errors.count, "error") %> found. 
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:page_title, "About") %>
<h1 class='center'>About</h1>
<br>
<p>Event Manager is a platform that allows users to create, manage, and sign up for events. It is another project intended to build and showcase my skills in Ruby on Rails. With that in mind, there is more emphasis on functionality than visual polish, although I may come back to this in the future. Features such as administrator access would also need to be added. For now, if you want a better idea of my CSS skills, please see my portfolio at <a href="http://markdking.me">http://markdking.me</a> or some of my other web apps in <a href="https://github.com/gute73">GitHub</a>.</p>

app/views/static_pages/home.html.erb
<%= provide(:page_title, "Home") %>
<h1 class='center'>Upcoming Events</h1>

<% if logged_in? %>
	<div class='create-event'>
		<%= link_to "Create an event", new_event_path %>
	</div>
<% end %>
<br>
<% if @upcoming_event_feed.any? %>
	<ol class='events'>
		<%= render @upcoming_event_feed %>
	</ol>
	<%= will_paginate @upcoming_event_feed %>
<% else %>
	<br>
	<p class='no-events'>No upcoming events!</p>
<% end %>

app/views/users/new.html.erb
<%= provide(:page_title, "Sign up") %>
<h1 class='center'>Sign up</h1>

<div class='row'>
	<div class='col-md-6 col-md-offset-3'>

		<%= form_for @user do |f| %>
	
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit 'Sign up', class: 'btn btn-primary' %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:page_title, @user.name) %>
<h1 class='center'><%= @user.name %></h1>

<% offset = "col-md-offset-3" %>
<% if logged_in? && current_user?(@user) %>
	<% offset = "" %>
<% end %>


<div class='row'>
	<div class="col-md-6 <%= offset %>">
		<h2 class='center'>Events Hosting</h2>
		<hr />

		<% if logged_in? && current_user?(@user) %>					
			<div class='create-event'>
				<%= link_to "Create an event", new_event_path %>
			</div>
			<br>
		<% end %>

		<% if @upcoming_hosted_event_feed.any? %>
			<%= render @upcoming_hosted_event_feed %>
		<% else %>
			<br>
			<p class='no-events'><%= @user.name %> is not hosting any upcoming events.</p>
		<% end %>
		<br>

		<h2 class='center'>Past Hosted Events</h2>
		<hr />
		<% if @past_hosted_event_feed.any? %>
			<%= render @past_hosted_event_feed %>
		<% else %>
			<br>
			<p class='no-events'><%= @user.name %> has no past hosted events.</p>
		<% end %>
		<br>
	</div>

	<% if logged_in? && current_user?(@user) %>
		<div class='col-md-6'>
			<h2 class='center'>Events Attending</h2>
			<hr />
			<% if @upcoming_attending_event_feed.any? %>
				<%= render @upcoming_attending_event_feed %>
			<% else %>
				<br>
				<p class='no-events'><%= @user.name %> is not attending any upcoming events.</p>
			<% end %>
			<br>

			<h2 class='center'>Past Attended Events</h2>
			<hr />
			<% if @past_attending_event_feed.any? %>
				<%= render @past_attending_event_feed %>
			<% else %>
				<br>
				<p class='no-events'><%= @user.name %> has not attended an event. </p>
			<% end %>
		</div>
	<% end %>
</div>